[env]
# Claude Code public
API_TIMEOUT_MS = "3000000"
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "1"

#ANTHROPIC_DEFAULT_HAIKU_MODEL = "glm-4.5-air"
#ANTHROPIC_DEFAULT_SONNET_MODEL = "glm-4.6"
#ANTHROPIC_DEFAULT_OPUS_MODEL = "glm-4.6"
